apiVersion: batch/v1
kind: Job
metadata:
  name: fiobench
spec:
  template:
    spec:
      containers:
      - name: fio
        image: ivotron/fio:latest
        resources:
          limits:
            cpu: "2"
          requests:
            cpu: "2"
        command: ["/bin/sh","-c"]
        args: ["mkdir tmp; fio --readwrite=read --ioengine=psync --direct=0 --iodepth=64 --bs=64k --size=1g --name=test_fio1 --directory=tmp --numjobs=2"]
      restartPolicy: Never
  backoffLimit: 4

